import updateClientRoles from "./updateClientRoles";
import createClients from "./createClients";
import startRedis from "./startRedis";
import RequestHandler from "..";

/**
 * Starts the request handler by:
 * - Creating the default client
 * - Creating the clients generated by the client generators.
 */
async function start(this: RequestHandler) {
  if (this.status !== "stopped") return;
  this.status = "starting";
  await startRedis.bind(this)();
  await createClients.bind(this)();
  await updateClientRoles.bind(this)(true);
  this.status = "started";
  this.emitter.emit("instanceStarted");
  this.logger.info(`Started request handler instance with ID ${this.id}`);
}

export default start;
