import updateClientRoles from "./updateClientRoles";
import createClients from "./createClients";
import startRedis from "./startRedis";
import RequestHandler from "..";

/**
 * Initializes the request handler by:
 * - Creating the default client
 * - Creating the clients generated by the client generators.
 */
async function initNode(this: RequestHandler) {
  if (this.isInitialized) return;
  await startRedis.bind(this)();
  await createClients.bind(this)();
  await updateClientRoles.bind(this)();
  this.isInitialized = true;
  this.emitter.emit("nodeInitialized");
  this.logger.info(`Initialized request handler node with ID ${this.id}`);
}

export default initNode;
